### PR TITLE
Response changed to nullable type, typo fixed.

### PR DESCRIPTION
**Pull request by vmetodiev**

### CODE REVIEW

**Comment by nightroman** [comment]
@vmetodiev Thank you for your contribution. I am reviewing it.
In the meantime, could you please let us know how the issue manifested itself?
- what were the steps to reproduce?
- what was the expected / actual result?

**Comment by vmetodiev** [comment]
@nightroman 
Query is kept exactly the same. However, for whatever reason the "diff" does not show the two lines that have actually been changed, but the whole file instead.

**Comment by nightroman** [comment]
For diff, use this option
image

**Comment by nightroman** [comment]
But this is not what my questions were about.

How did you get to the point of null result? So that you decided to change nullability. What input or other steps?

**Comment by vmetodiev** [comment]
It was due to a warning in VS Code - AFAIR one of the HttpClient method along the path could return a null in some edge case. However, I neither remember which one exactly, nor I have access to the environment to check.

The only "contribution" is the typo fix.

**Comment by nightroman** [comment]
Fair and clear answer. Let me investigate this, if it makes practical sense even in rare / exotic cases, then why not?

**Comment by nightroman** [comment]
>The only "contribution" is the typo fix.

It is still valuable, thank you for your time and effort.

**Comment by vmetodiev** [comment]
I may also try to "reproduce" the warning from VS Code. But no earlier than the beginning of next week.

**Comment by nightroman** [comment]
> I may also try to "reproduce" the warning from VS Code. But no earlier than the beginning of next week.

What are your VSCode C# related tools/extensions? I have `C# Dev Kit` and `C#` from Microsoft. They do not yield that warning or wiggles in the editor. 

I suggest the following: I merge the PR but for now leave only the typo correction actually accepted.
Then, with more information from you, here or in a new issue, we continue and deal with this case.

**Comment by vmetodiev** [comment]
Yep, sounds good.

**Pull request merged**
